version: '3.7'
services:
    frontend:
      container_name: sandbox-ui
      image: sandbox-ui
      restart: always
      privileged: true
      ports:
        - 80:80

    backend:
      container_name: sandbox-api
      image: sandbox-api
      restart: always
      privileged: true
      environment:
        - "IAM_TRUSTED_PROFILEID=__TRUSTED_PROFILE__" # Placeholder for IAM trusted profile
        - "IBM_SSHKEY_ID=__IBM_SSHKEY_ID__" # Placeholder for IBM Cloud SSH Key id
        - "DB_USERNAME=postgres"
        - "DB_PASSWORD=__DB_PASSWORD__" ## Placeholder for sandbox db password
        - "DB_HOST=sandbox-db"
        - "DB_PORT=5432"
        - "API_PORT=8080"
      ports:
        - 8080:8080
      volumes: 
        - ./ssh_keys:/usr/local/go/app/ssh_keys
        - ./montecarlo:/usr/local/go/app/montecarlo
        - ./huggingface:/usr/local/go/app/huggingface
      depends_on:
        - "db"

    db:
      container_name: sandbox-db  
      image: postgres:12.16
      restart: always
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=__DB_PASSWORD__ # Placeholder for sandbox db password
        - POSTGRES_DATABASE=ibm_sandbox
      logging:
        options:
          max-size: 10m
          max-file: "3"
      ports:
        - '5432:5432'
      volumes: 
        - ./db/psql-data:/var/lib/postgresql/data
        # copy the sql script to create tables
        - __DB_SCHEMA_SCRIPT__:/docker-entrypoint-initdb.d/create_tables.sql
